framework:
    messenger:
        buses:
            messenger.bus.default:
                middleware:
                    - App\Messenger\AuditMiddleware

        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    delay: 500
                    max_retries: 3
                    multiplier: 2
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: high
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            'App\Message\AddPonkaToImage': async_priority_high
            'App\Message\DeletePhotoFile': async

when@dev:
    framework:
        messenger:
            # transports:
            #     async: 'sync://'
            #     async_priority_high: 'sync://'
